#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-v$BUILD_NUMBER
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-v$BUILD_NUMBER
      task: test
  template:
    metadata:
      labels:
        app: test-v$BUILD_NUMBER
        task: test
        version: v0.0.1
    spec:
      containers:
      - name: test
        image: 47.97.63.218:5000/test/test:v$BUILD_NUMBER
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 50Mi
        #  limits:
        #    cpu: 100m
        #    memory: 50Mi
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regsecret
