#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
      task: test
  template:
    metadata:
      labels:
        app: test
        task: test
        version: v0.0.1
    spec:
      containers:
      - name: test
        image: 172.18.97.218:5000/test/test:v$BUILD_NUMBER
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 50Mi
        #  limits:
        #    cpu: 100m
        #    memory: 50Mi
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
        - name: docker-secret

---
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      name: web
      
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: test
          servicePort: http
